/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll;

import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gopinath
 */
public class FrmEmplogin extends javax.swing.JFrame {

    /**
     * Creates new form Emplogin
     */
    public FrmEmplogin() {
        initComponents();
        this.getContentPane().setBackground(Color.YELLOW);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProfile = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        btnLeaves = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContents = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblEmp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPLOYEE LOGIN");

        btnProfile.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnProfile.setText("My Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnAttendance.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnAttendance.setText("Attendance");
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });

        btnLeaves.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnLeaves.setText("Leaves");
        btnLeaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeavesActionPerformed(evt);
            }
        });

        tblContents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblContents);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("WECOME MESSAGE");

        btnLogout.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnLogout.setText("LOG OUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblEmp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblEmp.setText("Emp ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnProfile)
                                .addGap(149, 149, 149)
                                .addComponent(btnAttendance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLeaves)))))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lblEmp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addComponent(lblEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfile)
                    .addComponent(btnAttendance)
                    .addComponent(btnLeaves))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        Connect1 j=new Connect1();
        DBCollection dbc=j.connect("Emp_Records");
        BasicDBObject bdb=new BasicDBObject();
        bdb.put("ID",lblEmp.getText());
        
        
        
        String[] columnNames = {"Employee ID"," First Name","Last Name","Date Of Birth","Email ID","Address","Gender","Mobile","Date of joining","Designation"};
         DefaultTableModel dtm = new DefaultTableModel(columnNames,0);
         
         
       DBCursor cursor=dbc.find(bdb);
       if(cursor.hasNext()){
       DBObject obj = cursor.next();
       String ID=(String)obj.get("ID");
       String fname=(String)obj.get("First Name");
       String lname=(String)obj.get("Last Name");
        Date dob=(Date)obj.get("DOB");
       String gender=(String)obj.get("Gender");
       String phone=(String)obj.get("Mobile Number");
      Date doj=(Date)obj.get("DOJ");
       String desig=(String)obj.get("Designation");
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dob1 = sdf.format(dob);
        String doj1 = sdf.format(doj);
       String email=(String)obj.get("Email");
       String address=(String)obj.get("Address");
       
       
     dtm.addRow(new Object[]{ID,fname,lname,dob1,email,address,gender,phone,doj1,desig});
     clear();
       tblContents.setModel(dtm); 
       }
    }//GEN-LAST:event_btnProfileActionPerformed

    public void clear()
    {
       // tblContents.setModel(null);
    }
    
    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        // TODO add your handling code here:
        Connect1 j=new Connect1();
        DBCollection dbc=j.connect("Attendance");
        String[] columnNames = {"Date","Log in Time","Logout Time"};
        String inm="";
        String otm="";
         DefaultTableModel dtm = new DefaultTableModel(columnNames,0);
         BasicDBObject bdb=new BasicDBObject();
         bdb.put("Employee ID",lblEmp.getText());
        DBCursor cursor=dbc.find(bdb);
        while(cursor.hasNext())
        {
            DBObject obj=cursor.next();
            int date=(Integer)obj.get("Date");
            int month=(Integer)obj.get("Month");
            String dat=date+"/"+month+"/"+2015;
            if((int)obj.get("Login Minute")<10)
                inm="0"+(int)obj.get("Login Minute");
            else
                inm=""+(int)obj.get("Login Minute");
            if((int)obj.get("Logout Minute")<10)
                otm="0"+(int)obj.get("Logout Minute");
            else
                otm=""+(int)obj.get("Logout Minute");
            
            String loginTime=(int)obj.get("Login Hour")+":"+inm;
            String logoutTime=(int)obj.get("Logout Hour")+":"+otm;
             dtm.addRow(new Object[]{dat,loginTime,logoutTime});
       tblContents.setModel(dtm); 
            
        }
        
        
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnLeavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeavesActionPerformed
        // TODO add your handling code here:
        Calendar c=new GregorianCalendar();
        int month=c.get(Calendar.MONTH);
        int year=c.get(Calendar.YEAR);
        String[] columnNames = {"From","To","Number of days","Type"};
        DefaultTableModel dtm = new DefaultTableModel(columnNames,0);
        Connect1 j=new Connect1();
        DBCollection dbc=j.connect("leave");
        BasicDBObject bdb=new BasicDBObject();
        bdb.put("ID",lblEmp.getText());
        DBCursor cur=dbc.find(bdb);
        while(cur.hasNext())
        {
           
            DBObject obj=cur.next();
            if(((String)obj.get("ID")).equals(lblEmp.getText()))
            {
            int from=(Integer)obj.get("From");
            int to=(Integer)obj.get("To");
            String from_date=from+"/"+month+"/"+year;
            String to_date=to+"/"+month+"/"+year;
            String type=(String)obj.get("Type");
             dtm.addRow(new Object[]{from_date,to_date,to-from+1,type});
       tblContents.setModel(dtm);
            }
            else
                continue;
            
        }
    }//GEN-LAST:event_btnLeavesActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new FrmLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmplogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmplogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmplogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmplogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmplogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnLeaves;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblEmp;
    private static javax.swing.JTable tblContents;
    // End of variables declaration//GEN-END:variables

}
