/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll;

import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Gopinath
 */
public class FrmSalaryComp extends javax.swing.JFrame {

    /**
     * Creates new form SalaryComp
     */
    public FrmSalaryComp() {
        initComponents();
        this.getContentPane().setBackground(Color.yellow);
        setDefaultCloseOperation(this.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtEmpid = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblDDesignation = new javax.swing.JLabel();
        lblDOverrate = new javax.swing.JLabel();
        lblRph = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDNormalrate = new javax.swing.JLabel();
        lblDEmpid = new javax.swing.JLabel();
        lblDesig = new javax.swing.JLabel();
        lblOvertime = new javax.swing.JLabel();
        lblEmpId = new javax.swing.JLabel();
        lblDname = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblDCleaves = new javax.swing.JLabel();
        lblCasual = new javax.swing.JLabel();
        lblMedical = new javax.swing.JLabel();
        lblDSleaves = new javax.swing.JLabel();
        lblEmpID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblOhours = new javax.swing.JLabel();
        lblDWhours = new javax.swing.JLabel();
        lblDGross = new javax.swing.JLabel();
        lblDPresent = new javax.swing.JLabel();
        lblWhours = new javax.swing.JLabel();
        lblDOhours = new javax.swing.JLabel();
        lblGross = new javax.swing.JLabel();
        lblPdays = new javax.swing.JLabel();
        lblNetpay = new javax.swing.JLabel();
        lblMonthtemp = new javax.swing.JLabel();
        txtNetpay = new javax.swing.JTextField();
        mcMonth = new com.toedter.calendar.JMonthChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salary Calculation");
        setAutoRequestFocus(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 0));

        txtEmpid.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btnSubmit.setBackground(new java.awt.Color(153, 153, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.blue), "EMPLOYEE DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 2, 18))); // NOI18N

        lblDDesignation.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDDesignation.setText("Designation");

        lblDOverrate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDOverrate.setText("Overtime rate");

        lblRph.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblRph.setText("Rate per hour:");

        lblName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblName.setText("Name:");

        lblDNormalrate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDNormalrate.setText("Rate per hour");

        lblDEmpid.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDEmpid.setText("Employee Id");

        lblDesig.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDesig.setText("Designation:");

        lblOvertime.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblOvertime.setText("Overtime Rate:");

        lblEmpId.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblEmpId.setText("EmpId:");

        lblDname.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDname.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblOvertime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDOverrate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRph)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDNormalrate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblName)
                            .addComponent(lblEmpId)
                            .addComponent(lblDesig)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDname, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDEmpid, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpId)
                    .addComponent(lblDEmpid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(lblDname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesig)
                    .addComponent(lblDDesignation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRph)
                    .addComponent(lblDNormalrate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOvertime)
                    .addComponent(lblDOverrate))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "DEDUCTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 2, 18))); // NOI18N

        lblDCleaves.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDCleaves.setText("Casual Leaves");

        lblCasual.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCasual.setText("Casual Leaves:");

        lblMedical.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblMedical.setText("Sick Leaves:");

        lblDSleaves.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDSleaves.setText("Sick Leaves");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCasual)
                    .addComponent(lblMedical))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDSleaves)
                    .addComponent(lblDCleaves))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCasual)
                    .addComponent(lblDCleaves))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedical)
                    .addComponent(lblDSleaves))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblEmpID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmpID.setText("Employee ID:");

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.blue), "PAYROLL COMPUTATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 2, 18))); // NOI18N

        lblOhours.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblOhours.setText("Overtime Hours:");

        lblDWhours.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDWhours.setText("Working Hours");

        lblDGross.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDGross.setText("Gross Pay");

        lblDPresent.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDPresent.setText("Present days");

        lblWhours.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblWhours.setText("Working Hours:");

        lblDOhours.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDOhours.setText("Overtime Hours");

        lblGross.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblGross.setText("Gross Pay:");

        lblPdays.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblPdays.setText("Present Days:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPdays)
                        .addGap(39, 39, 39)
                        .addComponent(lblDPresent))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGross)
                        .addGap(55, 55, 55)
                        .addComponent(lblDGross))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblOhours)
                        .addGap(28, 28, 28)
                        .addComponent(lblDOhours))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblWhours)
                        .addGap(30, 30, 30)
                        .addComponent(lblDWhours)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPdays)
                    .addComponent(lblDPresent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWhours)
                    .addComponent(lblDWhours))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOhours)
                    .addComponent(lblOhours))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGross)
                    .addComponent(lblDGross))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        lblNetpay.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNetpay.setText("Net Pay:");

        lblMonthtemp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblMonthtemp.setText("For the Month of:");

        txtNetpay.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNetpay.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lblEmpID))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtEmpid, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnSubmit))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(lblMonthtemp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mcMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(lblNetpay)
                        .addGap(26, 26, 26)
                        .addComponent(txtNetpay, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(544, 544, 544))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMonthtemp)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblEmpID)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSubmit)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(mcMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNetpay)
                    .addComponent(txtNetpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String id=txtEmpid.getText();
        final JPanel p2=new JPanel();
        final JOptionPane jo=new JOptionPane();
        Connect1 j=new Connect1();
        DBCollection dbc=j.connect("Emp_Records");
        int month=mcMonth.getMonth();
        
        BasicDBObject search=new BasicDBObject();
        
        search.put("ID",id);
        DBCursor cur=dbc.find(search);
        if(cur.hasNext()==false)
        {
            JOptionPane.showMessageDialog(p2,"Enter Valid Employee ID","Failure",JOptionPane.ERROR_MESSAGE); 
            return;
        }
        else
        {
            DBObject obj=cur.next();
            lblDEmpid.setText((String)obj.get("ID"));
            lblDname.setText((String)obj.get("First Name")+" "+(String)obj.get("Last Name"));
            lblDDesignation.setText((String)obj.get("Designation"));
        }
       
        DBCollection dbc1=j.connect("Rates");
        BasicDBObject search1=new BasicDBObject();
        search1.put("Designation",lblDDesignation.getText());
         DBCursor cur1=dbc1.find(search1);
        
        
        DBObject obj=cur1.next();
        int nrate=(Integer)obj.get("Normal Rate");
        int orate=(Integer)obj.get("Overtime Rate");
        lblDNormalrate.setText((Integer)obj.get("Normal Rate")+"");
        lblDOverrate.setText((Integer)obj.get("Overtime Rate")+"");
        
        
        DBCollection dbc2=j.connect("Attendance");
        BasicDBObject search2=new BasicDBObject();
        search2.put("ID",txtEmpid.getText());
        search2.put("Month",month);
        int present_days=0;
        int whours=0;
        int ohours=0;
        int gross=0;
        int netpay=0;
        DBCursor cur2=dbc2.find();
        while(cur2.hasNext())
        {
            DBObject obj1=cur2.next();
            String ID=(String)obj1.get("Employee ID");
            int mon=(Integer)obj1.get("Month");
            if(mon!=month)
                break;
            if(ID.equals(txtEmpid.getText()))
            {
            if((Integer)obj1.get("Logout Hour")==-1)
            {
                continue;
            }
            else{                  
            present_days++;
            whours+=(Integer)obj1.get("Normal time");
            ohours+=(Integer)obj1.get("Overtime time");
            }
            }
                
            else
                    continue;
            
        } 
    
    
        gross+=nrate*whours;
        gross+=orate*ohours;
        lblDPresent.setText(present_days+"");
        lblDWhours.setText(whours+"");
        lblDOhours.setText(ohours+"");
        lblDGross.setText(gross+"");  
        
         
        DBCollection dbc3=j.connect("leave");
        BasicDBObject search3=new BasicDBObject();
         search3.put("ID",txtEmpid.getText());
         search3.put("Month",month);
        int cleaves=0;
        int sleaves=0;
        int paid_casual=0;
        int paid_sick=0;
        DBCursor cur3=dbc3.find(search3);
        while(cur3.hasNext())
        {
            DBObject obj1=cur3.next();
            String ID=(String)obj1.get("ID");
            String type=(String)obj1.get("Type");
            
      /*      if(mon!=month)
                break; */
            if(ID.equals(txtEmpid.getText()))
                            {
                              
          int start_date=(Integer) obj1.get("From");
          int end_date=(Integer) obj1.get("To");
          paid_casual+=(Integer)obj1.get("Paid_Casual");
          paid_sick+=(Integer)obj1.get("Paid_Sick");
          
          
          if(type.equals("Casual Leave"))
          {
              
              cleaves+=end_date-start_date+1;
              lblDCleaves.setText(cleaves+"");
           
                  
          }
          else
          {
              sleaves+=end_date-start_date+1;
              lblDSleaves.setText(sleaves+"");
          }  
          }
                
            else
                    continue;
            
        }
        DBCollection dbc4=j.connect("remaining_leaves");
        BasicDBObject bdb=new BasicDBObject();
        bdb.put("ID",txtEmpid.getText());
        DBCursor cur4=dbc4.find(bdb);
        DBObject obj4=cur4.next();
        int rcleaves=(Integer)obj4.get("Casual_leaves");
        int rsleaves=(Integer)obj4.get("Sick_leaves");
        

        int cleave_grant=8*nrate;
        cleave_grant*=paid_casual;
        netpay+=cleave_grant;
           
        int sleave_grant=8*nrate;
        sleave_grant*=sleaves;
        netpay+=sleave_grant;
        
        
        netpay+=gross;
       
        txtNetpay.setText(netpay+"");
            if(sleaves==0)
                lblDSleaves.setText("0");
            if(cleaves==0)
                lblDCleaves.setText("0");
                
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSalaryComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSalaryComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSalaryComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSalaryComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSalaryComp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCasual;
    private javax.swing.JLabel lblDCleaves;
    private javax.swing.JLabel lblDDesignation;
    private javax.swing.JLabel lblDEmpid;
    private javax.swing.JLabel lblDGross;
    private javax.swing.JLabel lblDNormalrate;
    private javax.swing.JLabel lblDOhours;
    private javax.swing.JLabel lblDOverrate;
    private javax.swing.JLabel lblDPresent;
    private javax.swing.JLabel lblDSleaves;
    private javax.swing.JLabel lblDWhours;
    private javax.swing.JLabel lblDesig;
    private javax.swing.JLabel lblDname;
    private javax.swing.JLabel lblEmpID;
    private javax.swing.JLabel lblEmpId;
    private javax.swing.JLabel lblGross;
    private javax.swing.JLabel lblMedical;
    private javax.swing.JLabel lblMonthtemp;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNetpay;
    private javax.swing.JLabel lblOhours;
    private javax.swing.JLabel lblOvertime;
    private javax.swing.JLabel lblPdays;
    private javax.swing.JLabel lblRph;
    private javax.swing.JLabel lblWhours;
    private com.toedter.calendar.JMonthChooser mcMonth;
    private javax.swing.JTextField txtEmpid;
    private javax.swing.JTextField txtNetpay;
    // End of variables declaration//GEN-END:variables
}
